import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Facebook, Twitter, Linkedin, Mail, Phone, MapPin, Instagram, Github } from "lucide-react";
import Logo from "../assets/ats-logo.png";
const Footer = () => {
    return (_jsx("footer", { className: "bg-gradient-to-r from-[#1a2940] to-[#1b273b]\n text-white", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-8", children: [_jsxs("div", { className: "col-span-1 md:col-span-2", children: [_jsxs("div", { className: "flex items-center mb-6", children: [_jsx("img", { src: Logo, alt: "Logo", className: "w-12 h-16 object-cover" }), _jsx("span", { className: "font-bold text-2xl text-white ml-3", children: "ATS GLOBAL TECH" })] }), _jsx("p", { className: "text-gray-300 mb-6 max-w-md leading-relaxed", children: "Empowering businesses with cutting-edge technology solutions. We specialize in custom software development, cloud solutions, AI implementation, and comprehensive digital transformation services." }), _jsxs("div", { className: "flex space-x-4", children: [_jsx("a", { href: "https://www.facebook.com/profile.php?id=61574788298611", children: _jsx(Facebook, { className: "h-8 w-8 text-gray-400 hover:text-orange-400 cursor-pointer transition-colors p-1 hover:bg-gray-800 rounded" }) }), _jsx("a", { href: "https://x.com/TechlabsSu58347", children: _jsx(Twitter, { className: "h-8 w-8 text-gray-400 hover:text-orange-400 cursor-pointer transition-colors p-1 hover:bg-gray-800 rounded" }) }), _jsx("a", { href: "https://www.linkedin.com/in/sudo-techlabs-8b6708375", children: _jsx(Linkedin, { className: "h-8 w-8 text-gray-400 hover:text-orange-400 cursor-pointer transition-colors p-1 hover:bg-gray-800 rounded" }) }), _jsx("a", { href: "https://www.instagram.com/in/sudo-techlabs-8b6708375", children: _jsx(Instagram, { className: "h-8 w-8 text-gray-400 hover:text-orange-400 cursor-pointer transition-colors p-1 hover:bg-gray-800 rounded" }) }), _jsx("a", { href: "https://www.github.com/in/sudo-techlabs-8b6708375", children: _jsx(Github, { className: "h-8 w-8 text-gray-400 hover:text-orange-400 cursor-pointer transition-colors p-1 hover:bg-gray-800 rounded" }) })] })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg mb-6 text-orange-400", children: "Quick Links" }), _jsx("ul", { className: "space-y-3", children: [
                                        { name: "About Us", href: "/about" },
                                        { name: "Services", href: "/services" },
                                        { name: "Solutions", href: "/solutions" },
                                        { name: "Industries", href: "/industries" },
                                        { name: "Projects", href: "/projects" },
                                        { name: "Portfolio", href: "/portfolio" },
                                        { name: "Case Studies", href: "/case-studies" },
                                        { name: "Careers", href: "/careers" },
                                    ].map((link) => (_jsx("li", { children: _jsx("a", { href: link.href, className: "text-gray-300 hover:text-orange-400 transition-colors", children: link.name }) }, link.name))) })] }), _jsxs("div", { children: [_jsx("h3", { className: "font-bold text-lg mb-6 text-orange-400", children: "Contact Info" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "flex items-start space-x-3", children: [_jsx(Mail, { className: "h-5 w-5 text-orange-400 mt-1 flex-shrink-0" }), _jsxs("div", { children: [_jsx("div", { className: "text-gray-300", children: "info@atsglobaltech.com" }), _jsx("div", { className: "text-gray-400 text-sm", children: "General inquiries" })] })] }), _jsxs("div", { className: "flex items-start space-x-3", children: [_jsx(Phone, { className: "h-5 w-5 text-orange-400 mt-1 flex-shrink-0" }), _jsxs("div", { children: [_jsx("div", { className: "text-gray-300", children: "+91 9929825003" }), _jsx("div", { className: "text-gray-400 text-sm", children: "24/7 Support" })] })] }), _jsxs("div", { className: "flex items-start space-x-3", children: [_jsx(MapPin, { className: "h-5 w-5 text-orange-400 mt-1 flex-shrink-0" }), _jsxs("div", { children: [_jsx("div", { className: "text-gray-300", children: "codercom building, A4, Ajmer Rd, Purani Chungi, Vidhyut Nagar, Jaipur                    Vaishali Nagar, Jaipur (302021)" }), _jsx("div", { className: "text-gray-400 text-sm", children: "Rajasthan, India" })] })] })] })] })] }), _jsx("div", { className: "border-t border-gray-800 mt-12 pt-8", children: _jsxs("div", { className: "flex flex-col md:flex-row justify-between items-center", children: [_jsxs("div", { className: "mb-4 md:mb-0", children: [_jsx("h3", { className: "font-bold text-lg mb-2 text-orange-400", children: "Stay Updated" }), _jsx("p", { className: "text-gray-300", children: "Subscribe to our newsletter for the latest tech insights and company updates." })] }), _jsxs("div", { className: "flex space-x-2", children: [_jsx("input", { type: "email", placeholder: "Enter your email", className: "px-4 py-2 bg-gray-800 border border-gray-700 rounded-lg text-white placeholder-gray-400 focus:outline-none focus:border-orange-400" }), _jsx("button", { className: "bg-gradient-to-r from-orange-500 to-red-500 px-6 py-2 rounded-lg text-white font-medium hover:opacity-90 transition-opacity", children: "Subscribe" })] })] }) }), _jsx("div", { className: "border-t border-gray-800 mt-8 pt-8 text-center", children: _jsxs("p", { className: "text-gray-400", children: ["\u00A9 2025 ATS GLOBAL TECH. All rights reserved. |", _jsx("span", { className: "ml-1 transition-colors hover:text-orange-400 cursor-pointer", children: "Privacy Policy" }), _jsx("span", { className: "ml-1 transition-colors hover:text-orange-400 cursor-pointer", children: "Terms of Service" })] }) })] }) }));
};
export default Footer;
