import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const FeatureCard = ({ title, desc, img, }) => (_jsxs("div", { className: "bg-[#112233] border border-[#1f3344] rounded-xl overflow-hidden hover:shadow-xl transition", children: [_jsx("img", { src: img, alt: title, className: "w-full h-44 object-cover" }), _jsxs("div", { className: "p-6", children: [_jsx("h4", { className: "text-lg font-semibold text-white mb-2", children: title }), _jsx("p", { className: "text-gray-300 text-sm leading-relaxed", children: desc })] })] }));
export default function SecureBankingApp() {
    return (_jsx("main", { className: "bg-gradient-to-b from-[#071928] to-[#0d2434] text-white min-h-screen py-32 px-4", children: _jsxs("div", { className: "max-w-7xl mx-auto", children: [_jsxs("section", { className: "grid gap-10 lg:grid-cols-2 items-center mb-20", children: [_jsxs("div", { children: [_jsx("span", { className: "text-sm bg-blue-900/40 text-blue-300 px-4 py-1 rounded-full", children: "Mobile Banking \u00B7 Secure" }), _jsx("h1", { className: "text-4xl md:text-5xl font-bold leading-tight mb-6", children: "Secure Banking Mobile App" }), _jsx("p", { className: "text-lg text-gray-300 max-w-xl leading-relaxed mb-8", children: "Designed for modern customers, this secure mobile banking solution offers instant fund transfers, biometric login, card controls, transaction insights, and 24/7 fraud detection \u2014 all powered by robust cloud security." }), _jsx("button", { className: "bg-blue-500 hover:bg-blue-600 text-black px-6 py-3 rounded-xl font-semibold shadow-lg", children: "Download App" })] }), _jsx("img", { src: "https://images.pexels.com/photos/4386328/pexels-photo-4386328.jpeg?auto=compress&cs=tinysrgb&w=1400", alt: "Banking App", className: "rounded-2xl shadow-lg w-full h-80 object-cover" })] }), _jsx("section", { className: "grid grid-cols-2 sm:grid-cols-4 gap-6 text-center mb-20", children: [
                        { label: "Transactions Secured", value: "45M+" },
                        { label: "Fraud Reduction", value: "82%" },
                        { label: "Active Users", value: "7.2M+" },
                        { label: "CSAT Rating", value: "4.8 / 5" },
                    ].map((stat) => (_jsxs("div", { children: [_jsx("p", { className: "text-3xl font-bold text-blue-400", children: stat.value }), _jsx("p", { className: "text-xs text-gray-400", children: stat.label })] }, stat.label))) }), _jsxs("section", { className: "mb-20", children: [_jsx("h2", { className: "text-2xl font-semibold mb-8", children: "Key Features" }), _jsxs("div", { className: "grid gap-6 sm:grid-cols-2 lg:grid-cols-3", children: [_jsx(FeatureCard, { title: "Biometric Authentication", desc: "Face & Fingerprint login ensures secure, fast access.", img: "https://images.unsplash.com/photo-1587731556938-38755b4803a6?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjh8fGltYWdlc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&q=60&w=1000" }), _jsx(FeatureCard, { title: "Instant Payments", desc: "UPI, NEFT, and QR-based transactions with real-time alerts.", img: "https://images.pexels.com/photos/4386370/pexels-photo-4386370.jpeg?auto=compress&cs=tinysrgb&w=1200" }), _jsx(FeatureCard, { title: "Fraud Protection", desc: "AI-driven detection flags suspicious activity instantly.", img: "https://images.pexels.com/photos/4968391/pexels-photo-4968391.jpeg?auto=compress&cs=tinysrgb&w=1200" })] })] }), _jsxs("section", { className: "mb-20", children: [_jsx("h2", { className: "text-2xl font-semibold mb-5", children: "Technology" }), _jsx("div", { className: "flex gap-3 flex-wrap", children: [
                                "React Native",
                                "Node.js",
                                "PostgreSQL",
                                "AWS",
                                "OAuth2.0",
                                "JWT",
                                "Microservices",
                                "Kotlin",
                            ].map((t) => (_jsx("span", { className: "px-3 py-1 bg-white/10 rounded-full text-sm text-gray-200", children: t }, t))) })] }), _jsxs("section", { className: "p-10 bg-[#092030] border border-[#153743] rounded-2xl text-center", children: [_jsx("h3", { className: "text-2xl font-semibold mb-3", children: "Secure Your Banking Experience" }), _jsx("p", { className: "text-gray-300 mb-6 max-w-xl mx-auto", children: "Banking made simple \u2014 fast, protected, and accessible anywhere." }), _jsx("button", { className: "bg-blue-500 hover:bg-blue-600 text-black px-8 py-3 rounded-full font-semibold", children: "Get Started Today" })] })] }) }));
}
